require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/audits", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Audit. As you add validations to Audit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Audit.create! valid_attributes
      get audits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      audit = Audit.create! valid_attributes
      get audit_url(audit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_audit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      audit = Audit.create! valid_attributes
      get edit_audit_url(audit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Audit" do
        expect {
          post audits_url, params: { audit: valid_attributes }
        }.to change(Audit, :count).by(1)
      end

      it "redirects to the created audit" do
        post audits_url, params: { audit: valid_attributes }
        expect(response).to redirect_to(audit_url(Audit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Audit" do
        expect {
          post audits_url, params: { audit: invalid_attributes }
        }.to change(Audit, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post audits_url, params: { audit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested audit" do
        audit = Audit.create! valid_attributes
        patch audit_url(audit), params: { audit: new_attributes }
        audit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the audit" do
        audit = Audit.create! valid_attributes
        patch audit_url(audit), params: { audit: new_attributes }
        audit.reload
        expect(response).to redirect_to(audit_url(audit))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        audit = Audit.create! valid_attributes
        patch audit_url(audit), params: { audit: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested audit" do
      audit = Audit.create! valid_attributes
      expect {
        delete audit_url(audit)
      }.to change(Audit, :count).by(-1)
    end

    it "redirects to the audits list" do
      audit = Audit.create! valid_attributes
      delete audit_url(audit)
      expect(response).to redirect_to(audits_url)
    end
  end
end
